imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @SCLeagueTeamBundle/Resources/config/admin.xml }
    - { resource: @SCLeagueSeasonBundle/Resources/config/admin.xml }
    - { resource: @SCLeagueUserBundle/Resources/config/admin.xml }
    - { resource: sonata/sonata_block.yml }




framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:


braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
    less_filter: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
      less:
          node: /usr/bin/node
          node_paths: [/usr/lib/node_modules]
          apply_to: "\.less$"
      cssrewrite: ~


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default

        entity_managers:
            default:
                auto_mapping: true
                mappings: ~

# Swiftmailer Configuration
swiftmailer:
    encryption: ssl
    auth_mode:  login
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }




fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SCLeague\UserBundle\Entity\User
#    group:
#        group_class:   SCLeague\UserBundle\Entity\Group
    registration:
      form:
        type: app_user_registration
      confirmation:
        enabled:    true
    resetting:
      email:
#        template: SelfUserBundle:User:resetting.email.html.twig
        from_email:
          address:        resetting@acmedemo.com
          sender_name:    Acme Demo Resetting



sonata_admin:
    dashboard:
        blocks:
            - { position: left, type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'><h3 class='panel-title'>Welcome!</h3></div><div class='panel-body'>You can customize this dashboard by editing the <code>sonata_admin.yml</code> file. The current dashboard presents the recent items from the NewsBundle and a non-statistical e-commerce information.</div></div>" } }

        groups:
            sonata.admin.group.season:
                label:  Season
                icon:   '<i class="fa fa-sitemap"></i>'
                items:
                    - sonata.admin.season
                    - sonata.admin.division

            sonata.admin.group.match :
                label:   Match
                icon:   <i class="fa fa-gamepad"></i>
                items:
                    - sonata.admin.team
                    - sonata.admin.game

            sonata.admin.group.administration:
                label:  sonata_administration
                label_catalogue: SonataAdminBundle
                icon:   '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.demo.admin.user
